- ```c++
  try
  {
   // здесь пробуем какой то код
   // если никаких исключений здесь не происходит, то catch не работает
   // если в этой области произошло какое то исключение, то будет выполняться блок catch
  }
  catch(const std::exception& ex)
  {
   //Код выполняется, если в блоке try появилось исключение
  }
  ```
- В блоке try можно кидать исключения, которые примет блок catch
  
  ```c++
  try{
  //some code
  std::string s = "aboba"
  throw s;
  }
  catch(std::string& s){
   std::cout << s << std::endl;
  }
  ```